// search-app/src/components/ui/PlaylistCard.tsx
import React, { useState, useEffect } from "react";
import { Playlist } from "@/constants/playlists";
import { getCurrentPlaylistId } from "@/lib/currentPlaylist";

interface PlaylistCardProps {
  playlist: Playlist;
}

export const PlaylistCard: React.FC<PlaylistCardProps> = ({ playlist }) => {
  const [isHovered, setIsHovered] = useState(false);
  const [currentPlaylistId, setCurrentPlaylistId] = useState<string | null>(
    getCurrentPlaylistId(),
  );

  const isNowPlaying = currentPlaylistId === String(playlist.id);

  const selectPlaylist = () => {
    window.dispatchEvent(
      new CustomEvent("sentio-playlist-selected", {
        detail: { playlist },
      }),
    );
  };

  useEffect(() => {
    const handlePlaylistSelected = () => {
      setCurrentPlaylistId(getCurrentPlaylistId());
    };

    window.addEventListener("sentio-playlist-selected", handlePlaylistSelected);

    return () => {
      window.removeEventListener(
        "sentio-playlist-selected",
        handlePlaylistSelected,
      );
    };
  }, []);

  return (
    <button
      type="button"
      className={`relative h-40 w-40 flex-shrink-0 cursor-pointer overflow-hidden rounded-2xl border shadow-md transition ${
        isNowPlaying
          ? "border-emerald-400/60 shadow-lg shadow-emerald-500/30"
          : "border-border/60"
      }`}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onClick={selectPlaylist}
    >
      <img
        src={playlist.image}
        alt={playlist.title}
        className={`h-full w-full object-cover transition ${isHovered ? "scale-105" : "scale-100"}`}
      />
      <div
        className={`absolute inset-0 bg-gradient-to-t via-transparent to-transparent transition ${
          isNowPlaying ? "from-emerald-500/30" : "from-black/60"
        } ${isHovered ? "opacity-100" : "opacity-0"}`}
      />
      <div
        className={`absolute inset-0 flex flex-col justify-end p-4 transition ${isHovered ? "opacity-100" : "opacity-0"}`}
      >
        <h3 className="text-sm font-semibold text-white">{playlist.title}</h3>
        <p className="text-xs text-emerald-300">{playlist.mood}</p>
      </div>
      <div
        className={`absolute inset-0 flex flex-col justify-end p-4 transition ${isHovered ? "opacity-0" : "opacity-100"}`}
      >
        <div
          className={`line-clamp-1 rounded-full px-2 py-1 text-xs font-medium backdrop-blur ${
            isNowPlaying
              ? "bg-emerald-500/30 text-emerald-50"
              : "bg-white/10 text-white"
          }`}
        >
          {playlist.mood}
        </div>
      </div>
    </button>
  );
};

// library-app/src/components/PlaylistCard.vue
<template>
  <article
    :class="[
      'group flex items-center gap-4 rounded-2xl border border-border bg-card/60 p-4 transition hover:border-emerald-400/40 hover:bg-card/80',
      isNowPlaying && 'bg-emerald-500/10 border-emerald-400/40',
    ]"
  >
    <div class="relative h-14 w-14 overflow-hidden rounded-2xl">
      <img
        :src="playlist.image"
        :alt="playlist.title"
        class="h-full w-full object-cover transition duration-300 group-hover:scale-105"
      />
      <div class="absolute inset-0 rounded-2xl ring-1 ring-border/60"></div>
    </div>

    <div class="min-w-0 flex-1">
      <div
        class="flex items-center gap-2 text-sm font-semibold text-foreground"
      >
        <Headphones size="14" class="text-emerald-400" />
        <span class="truncate">{{ playlist.title }}</span>
      </div>
      <p class="mt-1 flex items-center gap-2 text-xs text-muted-foreground">
        <Users size="12" class="text-muted-foreground/70" />
        <span class="truncate">{{ playlist.producers }}</span>
      </p>
    </div>

    <button
      type="button"
      class="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border bg-card/60 text-muted-foreground transition hover:border-emerald-400/40 hover:bg-emerald-500/20 hover:text-emerald-300"
      aria-label="Open playlist"
      @click="selectPlaylist"
    >
      <ChevronRight size="16" />
    </button>
  </article>
</template>

<script setup>
import { computed, ref, onMounted, onUnmounted } from "vue";
import { Headphones, Users, ChevronRight } from "lucide-vue-next";
import { getCurrentPlaylistId } from "../utils/currentPlaylist";

const props = defineProps({
  playlist: {
    type: Object,
    required: true,
  },
});

const currentPlaylistId = ref(getCurrentPlaylistId());

const isNowPlaying = computed(() => {
  return currentPlaylistId.value === String(props.playlist.id);
});

const selectPlaylist = () => {
  window.dispatchEvent(
    new CustomEvent("sentio-playlist-selected", {
      detail: { playlist: props.playlist },
    }),
  );
};

onMounted(() => {
  const handlePlaylistSelected = () => {
    currentPlaylistId.value = getCurrentPlaylistId();
  };

  window.addEventListener("sentio-playlist-selected", handlePlaylistSelected);

  onUnmounted(() => {
    window.removeEventListener(
      "sentio-playlist-selected",
      handlePlaylistSelected,
    );
  });
});
</script>
